name: Access PATH Environment Variable

on: 
   workflow_dispatch:

jobs:
  path_example:
    runs-on: windows-latest
    
    steps:
    - name: Display PATH
      run: echo $PATH
       
    - name: list directory
      run: |-
          dir
          "C:\Program Files\dotnet\dotnet.exe" --version
          "C:\Program Files\dotnet\dotnet.exe" --list-sdks
          echo ${PATH}
  Script_example:
     runs-on: ubuntu-latest
     steps:
     - name: Test
       shell: sh
       run: |-
          #!/bin/bash
          $BRANCH = feature/Build-TEST-Workflow:latest
          BRANCH_MOD = "$BRANCH_NAME" | tr / -
          echo $BRANCH_MOD
        
