name: Access PATH Environment Variable

on: 
   workflow_dispatch:

jobs:
  path_example:
    runs-on: windows-latest
    
    steps:
    - name: Display PATH
      run: echo $PATH      
   
  Script_example:
     runs-on: ubuntu-latest
     steps:
     - name: Test
       shell: bash
       run: |-
             #!/bin/bash
             $BRANCH = feature/Build-TEST-Workflow:latest
             BRANCH_MOD = "$BRANCH_NAME" | tr / -
             echo $BRANCH_MOD
           
