# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ReusableWorkflowartifact

on:
  workflow_dispatch:

jobs:
  build:
    
    uses: ./.github/workflows/uploadartifact.yml
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: Application_Artifact
        path: ./Package
        
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./Package
    - name: Unzip artifact
      run: unzip ./Package/Application_Artifact.zip
    
          
  
    
