# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ReusableWorkflowartifact

on:
  workflow_dispatch:

jobs:
  build:
    
    uses: ./.github/workflows/uploadartifact.yml
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      id: download
      with:
        name: Application_Artifact
        path: ./Package  
    - name: 'Echo download path'
      run: echo ${{steps.download.outputs.download-path}}
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./Package
    - name: Install DotCover nuget
      run: |
           Install-Package JetBrains.dotCover.CommandLineTools -Version 2021.1.0
           unzip dotCover.zip -d dotcover
    - name: Test
      run: dotnet test ./Package/TestProject1/TestProject1.dll --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Install DotCover
      run: |
           dotnet tool install --global JetBrains.dotCover.GlobalTool
    - name: Test
      run: dotnet test ./Package/TestProject1/TestProject1.dll --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
    - name: Test
      run: |
          
           dotnet dotcover test ./Package/TestProject1/TestProject1.dll --dcReportType=HTML --logger "console;verbosity=normal"
    

    
          
  
    
